### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by CarlosMFdz** [trevorsharp/youtubecast#10]
The SSL cert for [youtubecast.com](https://youtubecast.com/) appears to be expired.
I can access the website on my browser by adding an exception, but that can't be 
done on my podcast app so I'm unable to update/download anything.

**Comment by trevorsharp** [comment]
My server failed to renew the cert. Working on getting it updated now

**Comment by trevorsharp** [comment]
A valid cert has been added. I'll do some digging to figure out why my auto-renewal stopped working
