### ISSUE TITLE
Filtering out shorts

### ISSUE THREAD

**Issue by konopielko** [trevorsharp/youtubecast#11]
I think there should be an option to filter out shorts - they are meant to be consumed in a different way than regular videos therefore i believe they shouldn't be present in the feeds.
The YouTube API unfortunately doesn't return information if a video is a short - according to what I found the common way of checking if a video is a short is to make a request to the /shorts/ version of the URL and see if it redirects you to the regular version of the URL. I think the right approach would be to make this request only for videos that are at max 1 minute long and then if the parameter for filtering out shorts is present not list them in the feed.

**Comment by trevorsharp** [comment]
I added a new option to exclude YouTube shorts as you described. Thanks for the insight on how to find which videos are shorts!
