### ISSUE TITLE
@LettersLive channel errors out

### ISSUE THREAD

**Issue by driverkt** [trevorsharp/youtubecast#12]
Thanks for a great service!

I noticed today that https://youtube.com/@LettersLive seems to be erroring out. I'm not sure why since this seems to be a public channel. I've tried with both the `@LettersLive` id and the `UC4VK4LX8hbTjgdAipl0cHhw` id to no avail. 

See the below output: 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/1783591/214965259-00809d4b-19b1-4025-89ce-1d47bee0da86.png">

**Comment by trevorsharp** [comment]
Ah, I had some issues with my YouTube API key. This should be resolved now
