### ISSUE TITLE
Feed URLs not resolving/serving

### ISSUE THREAD

**Issue by 726a67** [trevorsharp/youtubecast#14]
The latest youtubecast docker image seems to be producing a routing error within my self-hosted instance; it looks like the service is able to resolve and ostensibly generate feed URLs for requested channels (1), but those feed URLs are not properly served, resulting in 404 errors when accessed by clients (2).

Note that my particular instance is served from behind a traefik reverse proxy, and that this issue was not present in youtubecast images pushed prior to 07/07/23.

_1._

`https://youtubecast.<domain>/linus%20tech%20tips`

![ytc-1](https://github.com/trevorsharp/youtubecast/assets/26912422/cede6cc1-0282-416a-b3fb-e66154436a30)

_2._

`https://youtubecast.<domain>/UCXuqSBlHAE6Xw-yeJA0Tunw/feed`

![ytc-2](https://github.com/trevorsharp/youtubecast/assets/26912422/c76a77b3-0815-4e06-9d70-4c15235c5559)

**Comment by trevorsharp** [comment]
I think I’ve identified the issue as a problem with Next13 and the internationalization (i18n) config when used with a reverse proxy in some cases. The docker image has been updated to remove the i18n config. Let me know if you continue to see this issue

**Comment by 726a67** [comment]
It looks like that fixed it; thanks for the quick turnaround!
