### ISSUE TITLE
Feeds no longer produce functional URLs

### ISSUE THREAD

**Issue by 726a67** [trevorsharp/youtubecast#15]
As of ~September 6th, it looks like the `<enclosure url>` fields within hosted feeds are no longer resolving to valid audio/video links. The rest of the feed appears to build correctly.

I've tested the public instance as well as a personal one; the same issue is present in both.

**Comment by trevorsharp** [comment]
Looks like there’s a new issue with the `ytdl-core` package. I’ve updated to a patched version of the package and it seems to be working now.
