### ISSUE TITLE
Problem to generate the rss feed for a YT playlist

### ISSUE THREAD

**Issue by nicks-technik** [trevorsharp/youtubecast#18]
I like to automatically generate a podcast rss feed from a Youtube playlist, but I have problem to generate the url. 
I tried different playlist/channels, but didn't get a working result.

E.g. when i put the following on the youtubecast.com website 
https://www.youtube.com/playlist?list=PL-56i5fRQDILa-YSZl--Qr47IQvv2qDQC 
The result in the middle shows, which has nothing to do, with my input playlist.
https://youtube.com/channel/UCtFRv9O2AHqOZjjynzrv-xg
The RSS shows
https://youtubecast.com/UCtFRv9O2AHqOZjjynzrv-xg/feed?excludeShorts
Pocket Casts shows:
pktc://subscribe/youtubecast.com/UCtFRv9O2AHqOZjjynzrv-xg/feed?excludeShorts

I tried the same stuff on a self hosted docker-compose instance. There the result is:
Could not find YouTube channel for id UCZHpIFMfoJJ_1QxNGLJTzyA

Do you have any idea, what the problem could be?

**Comment by trevorsharp** [comment]
The YouTube search with the full URL isn’t returning the playlist. You can search by just the playlist id (https://youtubecast.com/playlist?list=PL-56i5fRQDILa-YSZl--Qr47IQvv2qDQC). When I have some time, I can improve the search filtering

**Comment by nicks-technik** [comment]
YES, this works. 
Thank you very much for the service. I have read your README again, and it says channel name. So I was wrong with my input. Possibly you can add a hint to the readme, to make it more clear. 

One other question, what is the refresh interval on your youtubecast.com. If i self host it, can i set this interval somewhere because i like to have it hourly? 

I will try and thank you again.

**Comment by trevorsharp** [comment]
The generated feeds are cached for 20 minutes. And the playlist items from YouTube are cached for 30 minutes. So in the worst case, new items should appear on the feed within 50 minutes. Some podcast apps do their own caching on top of that, so it may be longer in those cases. 

The self-hosted version doesn’t have these cache times as dynamic parameters, but that may be something I could add in the future.

**Comment by nicks-technik** [comment]
Thank you for the feedback. 
Have a nice day
