### ISSUE TITLE
Chapter support [Feature request]

### ISSUE THREAD

**Issue by konopielko** [trevorsharp/youtubecast#3]
I love the project! It would be great if the podcasts (that have chapters on youtube) would also support chapters in the podcast app 😄
https://podcasters.apple.com/support/2482-using-chapters-on-apple-podcasts

**Comment by trevorsharp** [comment]
Unfortunately, the podcast chapters would have to be embedded into the media files directly, which won't work with this project's approach to stream the media from YouTube's servers to your device's podcast app. There's a potential that I could add this feature to my `youtubecast-videoserver` project, which serves the video files from a self-hosted server after downloading from YouTube. But that would come with all the drawbacks of having to self-host a solution.
