### ISSUE TITLE
Serverless deployment

### ISSUE THREAD

**Issue by konopielko** [trevorsharp/youtubecast#5]
It would be great if the project featured an option to automatically deploy to a serverless service - like vercel or netlify - I experimented with tuning the project so it works with vercel - but I stumbled on an issue with the fact that it requires for the python script to be inside of the /api route, which overwrites the pages/api route and so far I didn't manage to solve the issue

**Comment by trevorsharp** [comment]
In its current state, this project is not well suited for a serverless deployment solutions like Vercel. Aside from the reliance on multiple runtimes (Node.js and Python), this project makes heavy use of in-process caching to reduce YouTube API usage. Without this caching in place, the YouTube API usage would fairly easily exceed the daily quota. To work reliably on severless, this project would probably require a distributed caching solution as well as consolidating to a single runtime. I'm currently hosting the public version of this project ([youtubecast.com](https://youtubecast.com)) on DigitalOcean with a Linux box running in Docker, so the project has largely been designed to support that use case as well as self-hosted using Docker. 

I hope that helps clarify some of the challenges and tradeoffs that have gone into the project's current design.

**Comment by trevorsharp** [comment]
I merged your [PR #6](https://github.com/trevorsharp/youtubecast/pull/6) to only need the Node.js runtime. Thanks for finding that ytdl-core dependency!

This _should_ now work on serverless (albeit without the robust cache performance).
